spring:
  application:
    name: patient
  datasource:
    url: jdbc:mysql://localhost:3306/patient
    username: patient
    password: patient
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      driver-class-name: org.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect