services:
  mysql:
    image: mysql:8.1
    container_name: patient
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: patient
      MYSQL_USER: patient
      MYSQL_PASSWORD: patient
    restart: always